const WORD_LISTS = {
  Animals: [
  "aardvark", "adder", "agouti", "albatross", "alligator", "alpaca",
  "anaconda", "anchovy", "anemone", "angelfish", "anoa", "anole",
  "ant", "anteater", "antelope", "antlion", "ape", "aphid",
  "armadillo", "arowana", "avocet", "axolotl", "aye-aye", "baboon",
  "badger", "bandicoot", "barb", "barracuda", "bass", "bat",
  "bear", "beaver", "bee", "beetle", "beluga", "bighorn",
  "bilby", "binturong", "bison", "bittern", "blackbird", "blenny",
  "blowfly", "bluebird", "bluejay", "boa", "boar", "bobcat",
  "bobolink", "bonobo", "bowhead", "boxfish", "budgie", "buffalo",
  "bull", "bullfrog", "bumblebee", "bunting", "bushbaby", "bustard",
  "butterfly", "buzzard", "caiman", "camel", "canary", "capuchin",
  "capybara", "caracal", "cardinal", "caribou", "carp", "cat",
  "catbird", "catfish", "cattle", "cavy", "chameleon", "chamois",
  "cheetah", "chevrotain", "chickadee", "chicken", "chigger", "chimpanzee",
  "chinchilla", "chipmunk", "chital", "cicada", "civet", "clam",
  "clownfish", "coati", "cobra", "cockatoo", "cockle", "cockroach",
  "cod", "coelacanth", "colugo", "conch", "condor", "coral",
  "cormorant", "cougar", "cow", "cowbird", "coyote", "crab",
  "crane", "cricket", "crocodile", "crow", "cuckoo", "curlew",
  "cuscus", "cuttlefish", "damselfish", "damselfly", "danio", "deer",
  "devil", "dikdik", "dingo", "dobsonfly", "dog", "dolphin",
  "donkey", "dormouse", "dove", "dragonfly", "dragonet", "duck",
  "dugong", "duiker", "dung beetle", "eagle", "echidna", "eel",
  "egret", "eland", "elephant", "elk", "emu", "ermine",
  "falcon", "ferret", "finch", "firefly", "fisher", "flamingo",
  "flea", "flicker", "flounder", "fly", "flyingfish", "fossa",
  "fox", "frigatebird", "frog", "fulmar", "gadwall", "galago",
  "gannet", "gar", "gazelle", "gecko", "genet", "gerbil",
  "gibbon", "giraffe", "glowworm", "gnat", "goat", "goby",
  "godwit", "goldeneye", "goldfish", "goose", "gopher", "gorilla",
  "grackle", "grasshopper", "grebe", "grison", "grouper", "grouse",
  "guanaco", "guenon", "guppy", "gymnure", "hamster", "hare",
  "hartebeest", "harvestman", "hawk", "hedgehog", "hen", "heron",
  "herring", "hippo", "hoatzin", "hog", "honeybee", "hoopoe",
  "hornbill", "hornet", "horse", "housefly", "hoverfly", "hummingbird",
  "humpback", "hyena", "ibex", "ibis", "iguana", "impala",
  "indri", "jackal", "jaguar", "jaguarundi", "jay", "jellyfish",
  "jerboa", "kangaroo", "katydid", "kestrel", "kingfisher", "kinkajou",
  "kite", "kiwi", "klipspringer", "koala", "kob", "koi",
  "kookaburra", "kudu", "lacewing", "ladybug", "lamb", "lamprey",
  "langur", "lapwing", "lark", "lechwe", "lemming", "lemur",
  "leopard", "limpet", "lion", "lionfish", "lizard", "llama",
  "loach", "lobster", "locust", "loon", "lorikeet", "loris",
  "louse", "lovebird", "lungfish", "lynx", "macaque", "macaw",
  "mackerel", "magpie", "mallard", "mamba", "mammoth", "manatee",
  "mandrill", "manta", "mantis", "mara", "margay", "marlin",
  "marmoset", "marmot", "marten", "martin", "mastodon", "mayfly",
  "meadowlark", "meerkat", "merganser", "midge", "milkfish", "mink",
  "mite", "mockingbird", "mola", "mole", "mongoose", "monitor",
  "monkey", "moose", "moray", "mosquito", "moth", "mouflon",
  "mouse", "mudpuppy", "mudskipper", "mule", "muntjac", "muskox",
  "muskrat", "mussel", "myna", "narwhal", "nautilus", "newt",
  "nighthawk", "nightjar", "nudibranch", "numbat", "nuthatch", "nutria",
  "nyala", "ocelot", "octopus", "okapi", "olinguito", "opossum",
  "orangutan", "orca", "oriole", "oryx", "ostrich", "otter",
  "owl", "oyster", "paca", "paddlefish", "pademelon", "panda",
  "pangolin", "panther", "parrot", "parrotfish", "peacock", "peccary",
  "pelican", "penguin", "perch", "periwinkle", "petrel", "phalarope",
  "pheasant", "pig", "pigeon", "pike", "pintail", "piranha",
  "plaice", "planigale", "platypus", "pleco", "plover", "pochard",
  "polecat", "porcupine", "porcupinefish", "porpoise", "potoroo", "potto",
  "pronghorn", "pufferfish", "puffin", "puma", "python", "quagga",
  "quail", "quetzal", "quokka", "quoll", "rabbit", "raccoon",
  "rail", "rat", "rattlesnake", "raven", "ray", "razorbill",
  "redpanda", "reindeer", "rhea", "rhino", "rhinoceros", "robin",
  "roadrunner", "roedeer", "rook", "sable", "sailfish", "salamander",
  "salmon", "salp", "sambar", "sandpiper", "sardine", "sawfish",
  "scallop", "scaup", "scorpion", "scorpionfish", "scoter", "seadragon",
  "seahorse", "seal", "serval", "shag", "shark", "shearwater",
  "sheep", "shelduck", "shoveler", "shrew", "shrike", "siamang",
  "sifaka", "silkworm", "skate", "skimmer", "skink", "skua",
  "skunk", "sloth", "slug", "smew", "snail", "snake",
  "snapper", "snipe", "sole", "solenodon", "solifuge", "sparrow",
  "spider", "spoonbill", "springbok", "squid", "squirrel", "starfish",
  "starling", "stilt", "stingray", "stoat", "stonefish", "stork",
  "sturgeon", "sunfish", "swallow", "swan", "swift", "swordfish",
  "swordtail", "tamandua", "tamarin", "tanager", "tapir", "tarantula",
  "tarpon", "tarsier", "teal", "tegu", "tenrec", "termite",
  "tern", "tetra", "thrush", "thylacine", "tick", "tiger",
  "tilapia", "titmouse", "toad", "topi", "tortoise", "toucan",
  "treecreeper", "treeshrew", "triggerfish", "triton", "trout", "tuatara",
  "tuna", "turaco", "turbot", "turkey", "turnstone", "turtle",
  "urial", "vervet", "vicuña", "viper", "vole", "vulture",
  "wagtail", "wallaby", "wallaroo", "walleye", "walrus", "warbler",
  "warthog", "wasp", "waterbuck", "weasel", "weevil", "whale",
  "whelk", "whiptail", "whitefish", "wigeon", "wildebeest", "wolf",
  "wolverine", "wombat", "woodchuck", "woodcock", "woodpecker", "worm",
  "wrasse", "wren", "yak", "yellowjacket", "zebra", "zebu",
  "zokor"
],
  Countries: [
    "chad","cuba","fiji","iran","iraq","laos","mali","oman","peru","togo",
    "china","egypt","france","ghana","greece","haiti","india","italy","japan",
    "kenya","libya","nepal","niger","qatar","spain","sudan","syria","tonga",
    "wales","yemen",
    "angola","belize","bhutan","bosnia","brazil","brunei","canada","cyprus",
    "denmark","ecuador","eritrea","ethiopia","finland","gambia","georgia",
    "germany","grenada","guinea","hungary","iceland","ireland","israel",
    "jamaica","jordan","kuwait","latvia","lebanon","lesotho","liberia",
    "malawi","mexico","monaco","mongolia","morocco","myanmar","namibia",
    "nigeria","norway","pakistan","panama","poland","portugal","romania",
    "rwanda","senegal","serbia","slovakia","somalia","sweden","taiwan",
    "thailand","tunisia","turkey","uganda","ukraine","uruguay","vietnam",
    "zambia","zimbabwe",
    "afghanistan","argentina","australia","azerbaijan","bangladesh",
    "cambodia","cameroon","colombia","comoros","croatia","djibouti",
    "dominica","honduras","indonesia","kazakhstan","kyrgyzstan",
    "luxembourg","madagascar","malaysia","maldives","mauritius",
    "mozambique","nicaragua","paraguay","philippines","singapore",
    "slovenia","srilanka","tanzania","tajikistan","venezuela",
    "albania","andorra","armenia","austria","bahrain","belarus",
    "belgium","bolivia","bulgaria","burundi","czechia","estonia",
    "eswatini","gabon","grenada","guatemala","guinea","kiribati",
    "kosovo","latvia","liberia","liechtenstein","lithuania",
    "macedonia","moldova","montenegro","nauru","netherlands",
    "palestine","paraguay","romania","samoa","sanmarino",
    "senegal","serbia","seychelles","slovenia","suriname",
    "switzerland","tanzania","thailand","timorleste","tonga",
    "trinidadandtobago","tuvalu","uzbekistan","vanuatu",
    "vaticancity","venezuela","zimbabwe",
    "antiguaandbarbuda","bosniaandherzegovina","centralafricanrepublic",
    "dominicanrepublic","equatorialguinea","marshall","micronesia",
    "northkorea","papuanewguinea","saudiarabia","sierraleone",
    "solomon","southafrica","southsudan","stkittsandnevis",
    "stlucia","stvincentandthegrenadines","turkmenistan",
    "unitedkingdom","unitedstates","westernsahara"
],
  Movies: [
  "1917", "1922", "2012", "300", "1408", "83",
  "abominable", "agneepath", "airlift", "aladdin", "alien", "aliens",
  "anastasia", "animal", "annabelle", "annie", "annihilation", "ant-man",
  "antz", "aquaman", "argo", "armageddon", "arrival", "artist",
  "atlantis", "avatar", "aviator", "baaghi", "baazigar", "babu",
  "baby", "badla", "barbie", "barfi", "batman", "battleship",
  "beta", "bharat", "birdman", "black", "blackkklansman", "blade",
  "blood", "bodyguard", "bolt", "bombshell", "boss", "boyhood",
  "brahmastra", "brave", "braveheart", "brooklyn", "bull", "bumblebee",
  "cabin", "cars", "casino", "chappie", "chhichhore", "chicago",
  "christine", "cinderella", "cliffhanger", "coco", "coda", "cocktail",
  "company", "coraline", "crash", "croods", "cruella", "cujo",
  "dabangg", "dangal", "daredevil", "dark", "darr", "deadpool",
  "departed", "descent", "devdas", "deewaar", "deewana", "dhadak",
  "dhoom", "dil", "disenchanted", "divergent", "don", "doom",
  "dostana", "drishyam", "dumbo", "dune", "dunki", "dunkirk",
  "eldorado", "elektra", "elemental", "elf", "elysium", "encanto",
  "enchanted", "epic", "equalizer", "eragon", "evita", "exorcist",
  "fabelmans", "fan", "fanaa", "fargo", "favourite", "fences",
  "ferdinand", "firestarter", "flashdance", "fog", "footloose", "founder",
  "foxcatcher", "frankenweenie", "freaky", "frozen", "fury", "gadar",
  "ghajini", "glass", "gladiator", "godfather", "godzilla", "gold",
  "goldeneye", "goldfinger", "golmaal", "goodfellas", "goon", "goosebumps",
  "gravity", "grease", "grinch", "grudge", "gunday", "hairspray",
  "halloween", "happening", "harriet", "heat", "her", "hercules",
  "hereditary", "hero", "highway", "hitman", "holes", "home",
  "hook", "hop", "horton", "housefull", "hugo", "hulk",
  "hum", "hungama", "hush", "hustle", "ice", "inception",
  "incredibles", "inkheart", "insidious", "interstellar", "irishman",
  "it", "jackie", "jaws", "jawan", "joker", "judy",
  "jumanji", "kaante", "kahaani", "kaminey", "kedarnath", "kesari",
  "kgf", "khalnayak", "khiladi", "kick", "krrish", "labyrinth",
  "lagaan", "land", "legend", "life", "lighthouse", "lightyear",
  "limitless", "lincoln", "lion", "logan", "lola", "looper",
  "lorax", "love", "loving", "luca", "lucy", "madagascar",
  "maid", "maleficent", "manikarnika", "martian", "masti", "matrix",
  "maxxxine", "megamind", "men", "midsommar", "migration", "milk",
  "minari", "minions", "mirrors", "misery", "mist", "moana",
  "mohabbatein", "mom", "moon", "moonlight", "moonraker", "morbius",
  "mud", "mudbound", "mulan", "mulk", "munich", "mute",
  "nanny", "neighbors", "nightcrawler", "nine", "noah", "nomadland",
  "nope", "notorious", "nowhere", "nun", "nuts", "oblivion",
  "octopussy", "old", "omerta", "once", "onward", "oppenheimer",
  "orphan", "oslo", "paa", "padmaavat", "paranorman", "parmanu",
  "passengers", "pathaan", "patriot", "paul", "pearl", "pinocchio",
  "piku", "pk", "planes", "platoon", "pocahontas", "post",
  "predator", "prey", "prometheus", "proof", "prospect", "psycho",
  "pulse", "purge", "pushpa", "queen", "ra-one", "raazi",
  "race", "radhe", "raees", "rain", "raja", "ram-leela",
  "rambo", "ratatouille", "rawson", "ready", "rebecca", "red",
  "rent", "requiem", "revenant", "riddick", "ride", "ring",
  "rio", "road", "robocop", "rockstar", "rocky", "room",
  "rope", "rrr", "ruins", "rush", "rustom", "sabotage",
  "saboteur", "salaar", "salt", "samsara", "saw", "scarface",
  "scoob", "scream", "selma", "serenity", "seven", "shaft",
  "shame", "shazam", "shining", "sholay", "short", "shot",
  "shrek", "shutter", "sign", "silence", "simmba", "sinister",
  "sing", "singham", "skyfall", "smallfoot", "snatch", "sooryavanshi",
  "soul", "source", "spectre", "speed", "spellbound", "spider-man",
  "spider-verse", "split", "spotlight", "stardust", "stay", "steel",
  "storks", "strangers", "street", "stretch", "stuber", "stunts",
  "sugar", "sully", "sunshine", "super", "superman", "suspicion",
  "taal", "taken", "tangled", "tanhaji", "tarzan", "tekken",
  "tenet", "terminal", "terminator", "thing", "thinner", "thor",
  "thumbelina", "thunderball", "time", "titanic", "together", "touch",
  "traffic", "train", "transcendence", "transformers", "trick", "trolls",
  "tron", "trust", "truth", "tumbbad", "turbo", "tusk",
  "twilight", "twister", "ulysses", "unbreakable", "uncharted", "under",
  "undertow", "unity", "up", "uri", "us", "vampires",
  "venom", "vertigo", "vice", "vigil", "village", "violet",
  "visit", "vivo", "volcano", "voyage", "wall-e", "wanda",
  "war", "warcraft", "warm", "watchmen", "whiplash", "wild",
  "willow", "wish", "witch", "wolf", "wonder", "wonder",
  "x-men", "zathura", "zero", "zombieland", "zootopia"
],
  Fruits: [
  "acai", "ackee", "apple", "apricot", "avocado",
  "banana", "baobab", "berry", "bilberry", "blackberry",
  "bloodorange", "blueberry", "boysenberry", "breadfruit",
  "buddhahand", "cantaloupe", "carambola", "cashewapple",
  "cherimoya", "cherry", "chokeberry", "citron", "citrus",
  "clementine", "cloudberry", "coconut", "crabapple",
  "cranberry", "cumquat", "currant", "custardapple",
  "damson", "date", "dewberry", "dragonfruit", "durian",
  "elderberry", "feijoa", "fig", "fingerlime", "gooseberry",
  "grape", "grapefruit", "guava", "hackberry", "honeydew",
  "hornedmelon", "huckleberry", "jackfruit", "jambul",
  "jujube", "juniperberry", "kiwano", "kiwi", "kumquat",
  "lemon", "lime", "lingonberry", "loganberry", "loquat",
  "lychee", "mandarin", "mango", "mangosteen", "marionberry",
  "medlar", "melon", "miraclefruit", "monstera", "mulberry",
  "nance", "nectarine", "olive", "orange", "papaya",
  "passionfruit", "pawpaw", "peach", "pear", "pepino",
  "persimmon", "pineapple", "pitaya", "plantain", "plum",
  "pluot", "pomegranate", "pomelo", "pricklypear",
  "prune", "quince", "raisin", "rambutan", "raspberry",
  "redcurrant", "rosehip", "salak", "santol", "sapodilla",
  "satsuma", "serviceberry", "soursop", "starfruit",
  "strawberry", "sugarapple", "sultana", "surinamcherry",
  "tamarillo", "tamarind", "tangelo", "tangerine",
  "tomato", "ugli", "watermelon", "whitecurrant",
  "yuzu"
],
  Sports: [
  "aikido","airsoft","archery","armwrestling","athletics",
  "backgammon","badminton","bandy","baseball","basketball",
  "beachvolleyball","biathlon","billiards","bmx","bobsled",
  "bodyboarding","bowling","box","boxing","bridge",
  "broomball","bullriding","bungee","canoeing","capoeira",
  "cheerleading","chess","climbing","cricket","croquet",
  "crosscountry","crossfit","curling","cycling","darts",
  "decathlon","discus","dive","diving","dodgeball",
  "dragracing","dressage","equestrian","eventing","fencing",
  "fieldhockey","figureskating","fishing","football","freediving",
  "freestyle","frisbee","futsal","go","golf",
  "gymnastics","hammerthrow","handball","heptathlon","highjump",
  "hiking","hockey","horsebackriding","hurling","icehockey",
  "iceskating","inline","javelin","jogging","judo",
  "jujitsu","kabaddi","karate","karting","kayaking",
  "kendo","kickboxing","kitesurfing","kungfu","lacrosse",
  "lasertag","longjump","luge","marathon","mma",
  "motocross","mountaineering","muaythai","netball","nordiccombined",
  "openwater","orienteering","paddleboard","paintball","parkour",
  "pickleball","polo","pool","polevault","powerlifting",
  "quidditch","racewalking","racing","racquetball","rafting",
  "rally","rhythmicgymnastics","rockclimbing","rollerskating","rowing",
  "rugby","run","sailing","shooting","shotput",
  "showjumping","skateboarding","skating","skeleton","ski",
  "skijumping","skiing","skydiving","snooker","snowboarding",
  "soccer","softball","speedskating","squash","steeplechase",
  "sumo","sup","surf","surfing","swim",
  "swimming","synchronizedswimming","tabletennis","taekwondo","tennis",
  "track","trampoline","triathlon","triplejump","ultimate",
  "volleyball","wakeboarding","waterpolo","weightlifting","windsurfing",
  "wrestling"
],
  Foods: [
  "acai","agave","alfalfa","amaranth","anchovy",
  "applesauce","artichoke","asparagus","avocado",
  "bacon","bagel","baguette","baklava","banana",
  "barley","basil","bean","beet","berry","biryani",
  "biscotti","biscuit","blackberry","blini","blueberry",
  "bologna","bouillon","bread","brioche","broccoli",
  "broth","brownie","bruschetta","bulgur","bun",
  "burrito","butter","buttermilk","cabbage","cake",
  "calzone","candy","cannoli","cantaloupe","caramel",
  "carrot","cashew","casserole","caviar","celery",
  "cereal","ceviche","chard","cheese","cheesecake",
  "cherry","chestnut","chicken","chickpea","chili",
  "chip","chips","chive","chocolate","chop",
  "chowder","chutney","ciabatta","cider","cilantro",
  "cinnamon","clam","clove","cobbler","coconut",
  "cod","coffee","collards","cookie","corn",
  "cornbread","crab","cracker","cranberry","cream",
  "crepe","croissant","crouton","crumpet","cucumber",
  "cumin","cupcake","currant","curry","custard",
  "daikon","dal","date","dill","dip","donut",
  "dosa","doughnut","dressing","dumpling","durian",
  "eclair","edamame","eel","egg","eggplant",
  "elderberry","empanada","enchilada","endive","escargot",
  "espresso","falafel","farfalle","fennel","feta",
  "fettuccine","fig","filet","fish","flan","flax",
  "focaccia","foiegras","fritter","frosting","fruit",
  "fudge","garlic","gazpacho","gelato","ginger",
  "gnocchi","goulash","granola","grape","grapefruit",
  "gravy","grits","guacamole","guava","gyro",
  "halibut","halvah","ham","hamburger","hazelnut",
  "herring","honey","honeydew","hotdog","hummus",
  "icecream","icing","jackfruit","jam","jambalaya",
  "jelly","jerky","juice","kale","kebab","ketchup",
  "kielbasa","kimchi","kiwi","kohlrabi","kombucha",
  "kumquat","lamb","lasagna","latte","leek",
  "lemon","lentil","lettuce","licorice","lime",
  "linguine","lobster","loaf","loin","lox",
  "lychee","macadamia","macaroni","mackerel","mango",
  "maple","marinara","marzipan","mayo","meatball",
  "meatloaf","melon","meringue","milk","millet",
  "mint","miso","molasses","mousse","mozzarella",
  "muffin","mulberry","mushroom","mussel","mustard",
  "mutton","naan","nectarine","noodle","nougat",
  "nut","nutella","nutmeg","oat","oatmeal","octopus",
  "oil","okra","olive","omelet","onion","orange",
  "oregano","oyster","paella","pancake","paneer",
  "papaya","paprika","parfait","parmesan","parsley",
  "parsnip","passionfruit","pasta","pastrami","pate",
  "patty","peach","peanut","pear","peas","pecan",
  "penne","pepper","pepperoni","persimmon","pesto",
  "pickle","pie","pilaf","pimento","pineapple",
  "pistachio","pita","pizza","plantain","plum",
  "poached","polenta","pomegranate","popcorn","popsicle",
  "pork","porridge","potato","pretzel","pudding",
  "pumpkin","punch","quiche","quinoa","radish",
  "ragu","raisin","rambutan","raspberry","ratatouille",
  "ravioli","relish","rhubarb","rice","ricotta",
  "risotto","roll","romaine","roti","rutabaga",
  "rye","saffron","sage","salad","salami","salmon",
  "salsa","samosa","sandwich","sardine","sashimi",
  "sauerkraut","sausage","scallion","scallop","scone",
  "scones","scrambled","seitan","shallot","shrimp",
  "slaw","smoothie","snapper","sorbet","souffle",
  "soup","sourdough","soy","spaghetti","spareribs",
  "spice","spinach","sprout","squash","squid",
  "steak","stew","stirfry","strawberry","strudel",
  "succotash","sundae","sushi","syrup","taco",
  "tagine","tahini","tamale","tangelo","tangerine",
  "tapioca","tarragon","tart","tartare","tea",
  "tempura","tequila","teriyaki","thyme","tilapia",
  "tiramisu","toast","toffee","tofu","tomatillo",
  "tomato","tortilla","trifle","tripe","trout",
  "truffle","tuna","turkey","turmeric","turnip",
  "udon","vanilla","veal","venison","vermicelli",
  "vinegar","vodka","waffle","walnut","wasabi",
  "watermelon","wheat","wonton","yam","yogurt",
  "zest","ziti","zucchini"
],
  Elements: [
  "actinium","aluminium","aluminum","americium","antimony","argon",
  "arsenic","astatine","barium","berkelium","beryllium","bismuth",
  "bohrium","boron","bromine","cadmium","caesium","calcium",
  "californium","carbon","cerium","cesium","chlorine","chromium",
  "cobalt","copernicium","copper","curium","darmstadtium","dubnium",
  "dysprosium","einsteinium","erbium","europium","fermium","flerovium",
  "fluorine","francium","gadolinium","gallium","germanium","gold",
  "hafnium","hassium","helium","holmium","hydrogen","indium",
  "iodine","iridium","iron","krypton","lanthanum","lawrencium",
  "lead","lithium","livermorium","lutetium","magnesium","manganese",
  "meitnerium","mendelevium","mercury","molybdenum","moscovium",
  "neodymium","neon","neptunium","nickel","nihonium","niobium",
  "nitrogen","nobelium","oganesson","osmium","oxygen","palladium",
  "phosphorus","platinum","plutonium","polonium","potassium",
  "praseodymium","promethium","protactinium","radium","radon",
  "rhenium","rhodium","roentgenium","rubidium","ruthenium",
  "rutherfordium","samarium","scandium","seaborgium","selenium",
  "silicon","silver","sodium","strontium","sulfur","sulphur",
  "tantalum","technetium","tellurium","tennessine","terbium",
  "thallium","thorium","thulium","tin","titanium","tungsten",
  "uranium","vanadium","xenon","ytterbium","yttrium","zinc",
  "zirconium"
],
  Vehicles: [
  "aeroplane","aircraft","airliner","airplane","airship","ambulance",
  "amphibian","apc","armoredcar","armoredtruck","atv","auto",
  "autogyro","autorickshaw","backhoe","balloon","barge","battleship",
  "bicycle","biplane","blimp","boat","bomber","buggy","bulldozer",
  "bus","cab","cablecar","camper","campervan","canoe","capsule",
  "car","caravan","cargoplane","cargoship","carriage","carrier",
  "cart","catamaran","chariot","chopper","clipper","coach",
  "combine","containership","convertible","coracle","corvette","coupe",
  "crane","crossover","cruiser","cutter","cycle","destroyer",
  "dhow","dinghy","dirtbike","dirigible","dogsled","dolly",
  "dredger","drone","dukw","dumptruck","eunicycle","ebike",
  "ekranoplan","electricbike","electriccar","electricunicycle","excavator",
  "felucca","ferry","fighter","fireengine","firetruck","floatplane",
  "flyingboat","foodtruck","forklift","freighter","frigate",
  "funicular","galleon","glider","gocart","golfcart","gondola",
  "grader","gyrocopter","halftrack","handcar","handtruck","hangglider",
  "harvester","hatchback","helicopter","heli","hoverboard","hovercraft",
  "houseboat","humvee","hydrofoil","icebreaker","ifv","jeep",
  "jet","jetboat","jetliner","jetski","jumbojet","junk",
  "kayak","ketch","kickscooter","lander","lifeboat","liferaft",
  "lightrail","limo","limousine","liner","loader","locomotive",
  "longboard","lorry","maglev","metro","microlight","minivan",
  "mixer","mobilityscooter","monorail","moonbuggy","moped","motorbike",
  "motorboat","motorcycle","motorhome","mower","onewheel","orbiter",
  "osprey","outrigger","oxcart","paddleboat","paver","pedalboat",
  "pedicab","pickup","plane","policecar","pontoon","powerboat",
  "pram","proa","punt","pwc","quadcopter","raft",
  "railcar","rickshaw","roadster","rocket","roller","rover",
  "rowboat","runabout","rv","sailboat","sailplane","sampan",
  "schooner","scooter","scraper","seaplane","sedan","segway",
  "semitrailer","ship","shuttle","skateboard","skates","skiff",
  "sled","sleigh","sloop","snowcat","snowmobile","snowplow",
  "spacecraft","spaceplane","spaceship","spaceshuttle","sprayer",
  "stagecoach","stealth","streetcar","stroller","submarine",
  "submersible","subway","suv","tandem","tank","tanker",
  "taxi","taxicab","tiltrotor","toboggan","tractor","trailer",
  "train","tram","tramcar","tricycle","trimaran","trolley",
  "trolleybus","truck","tugboat","tuktuk","ultralight","unicycle",
  "utv","van","velocipede","wagon","warship","waverunner",
  "wheelchair","windsurfer","yacht","yawl","zeppelin"
]
};

const CATEGORIES = Object.keys(WORD_LISTS);
const RARE_LETTERS = new Set(['q','x','z','j','k','v','w','y']);
const VERY_RARE = new Set(['q','x','z']);

function validateWord(word, category) {
  const w = word.toLowerCase().trim();
  if (!w || w.length < 2) return false;
  const list = WORD_LISTS[category];
  if (!list) return false;
  return list.includes(w);
}

function getRandomCategory() {
  return CATEGORIES[Math.floor(Math.random() * CATEGORIES.length)];
}

function getRandomWord(category, usedWords = []) {
  const list = WORD_LISTS[category] || [];
  const available = list.filter(w => !usedWords.includes(w));
  if (available.length === 0) return null;
  return available[Math.floor(Math.random() * available.length)];
}

function getWordsByLength(category, minLen, usedWords = []) {
  const list = WORD_LISTS[category] || [];
  const available = list.filter(w => w.length >= minLen && !usedWords.includes(w));
  if (available.length === 0) return getRandomWord(category, usedWords);
  return available[Math.floor(Math.random() * available.length)];
}

function calculateDamage(word, submissionTime, roundDuration) {
  if (!word) return 0;
  const w = word.toLowerCase();
  let damage = w.length;
  let rarebonus = 0;
  for (const ch of w) {
    if (VERY_RARE.has(ch)) rarebonus += 3;
    else if (RARE_LETTERS.has(ch)) rarebonus += 1;
  }
  damage += rarebonus;
  const ratio = Math.max(0, 1 - submissionTime / roundDuration);
  const speedBonus = Math.floor(ratio * 5);
  damage += speedBonus;
  return damage;
}

module.exports = {
  WORD_LISTS,
  CATEGORIES,
  validateWord,
  getRandomCategory,
  getRandomWord,
  getWordsByLength,
  calculateDamage
};
